name: "github-action-auto-context"
description: "Automaticaly open a pull request to update context.tf for Terraform projects"
inputs:
  branch-name:
    description: "Name of branch to commit updated context.tf to"
    required: false
    default: "auto-update/context.tf"
  token:
    description: "Token for authenticating to GitHub API server. No special permissions needed."
    required: true
  bot-name:
    description: "Username to write commits under"
    required: false
    default: "cloudpossebot"
  bot-email:
    description: "Email to write commits under"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Set bot-email to GitHub default if inputs.bot-email not provided"
      id: bot-email-set
      shell: bash
      run: |
        if [ -z ${{ inputs.bot-email }} ]; then
          bot_id=$(curl -sSL 'https://api.github.com/users/${{ inputs.bot-name }}' | jq .id)
          bot_email=${bot_id}+${{ inputs.bot-name }}@users.noreply.github.com
        else
          bot_email=${{ inputs.bot-email }}
        fi
        echo "::set-output name=bot-email::${bot_email}"

    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Update context.tf, checkout new branch, and commit new context.tf, if needed"
      id: update
      uses: docker://cloudposse/build-harness:latest
      with:
        entrypoint: /github/workspace/context_update.sh
      env:
        BRANCH_NAME: ${{ inputs.branch-name }}
        HOST_REPO: ${{ github.repository }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        committer: '${{ inputs.bot-name }} <${{steps.bot-email-set.outputs.bot-email}}>'
        author: '${{ inputs.bot-name }} <${{steps.bot-email-set.outputs.bot-email}}>'
        commit-message: Update context.tf from origin source
        title: Update context.tf
        body: |-
          ## what
          This is an auto-generated PR that updates the `context.tf` file to the latest version from `cloudposse/terraform-null-label`
          ## why
          To support all the features of the `context` interface.
        branch: auto-update/context.tf
        base: ${{ github.event.repository.default_branch }}
        delete-branch: true
        labels: |
          auto-update
          context
