name: "github-action-auto-context"
description: "Automaticaly open a pull request to update context.tf for Terraform projects"
inputs:
  app_checkout_path:
    description: 'The path to checkout the application repository to during the workflow run'
    default: ./github-action-auto-context
    required: false
  branch-name:
    description: "Name of branch to commit updated context.tf to"
    required: false
    default: "auto-update/context.tf"
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

#    - name: "Checkout github-action-auto-context repo to load script locally on runner"
#      uses: actions/checkout@v2
#      with:
#        repository: cloudposse/github-action-terraform-auto-context@main
#        path: ${{ inputs.app_checkout_path }}

    - name: "Update context.tf, checkout new branch, and commit new context.tf, if needed"
      shell: bash
      id: update
      env:
        BRANCH_NAME: ${{ inputs.branch-name }}
      run: |
        if [[ -f context.tf ]]; then
          echo "Discovered existing context.tf!"
          echo "Checking for pre-existing ${BRANCH_NAME} branch."
          if [[ ! $(git show-branch remotes/origin/${BRANCH_NAME}) ]]; then
            echo "Branch ${BRANCH_NAME} not found."
            echo "Fetching most recent version of context.tf to see if there is an update."
            curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
            if git diff --no-patch --exit-code context.tf; then
              echo "No changes detected! Exiting the job..."
            else
              # updating context.tf and documentation
              echo "context.tf file has changed. Update examples and rebuild README.md and commit everything to a new ${BRANCH_NAME} branch."
              make init
              make github/init/context.tf
              make readme/build
              # moving to new branch to commit changes
              git checkout -b ${BRANCH_NAME}
              # committing changes
              git config --global user.name 'cloudpossebot'
              git config --global user.email '11232728+cloudpossebot@users.noreply.github.com'
              git add -A
              git commit -m "Update context.tf from origin source"
              git push --set-upstream origin ${BRANCH_NAME}
              # setting flag to create pull request for new branch
              echo "::set-output name=create_pull_request::true"
            fi
          else
            echo "Branch ${BRANCH_NAME} found."
            echo "Please merge pre-existing ${BRANCH_NAME} branch before rerunning this action."
          fi
        else
          echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
        fi

    - name: "Output pull request body"
      shell: bash
      run: |
        #PR_BODY=$(cat ${{ inputs.app_checkout_path }}/pr_body.txt)
        PR_BODY=$(cat ${GITHUB_ACTION_PATH}/pr_body.txt)
        echo PR_BODY=${PR_BODY} >> $GITHUB_ENV

    - name: "Parse Repo Name"
      shell: bash
      env:
        FULL_REPO_NAME: ${{ github.repository }}
      run: |
        REPO_BASENAME=$(basename $FULL_REPO_NAME)
        echo "REPO_NAME=$REPO_BASENAME" >> $GITHUB_ENV

    - name: Create Pull Request
      if: steps.update.outputs.create_pull_request == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          // extract the base branch name that's being merged into
          let prBaseRef = context.ref;

          // create pull request
          github.pulls.create({
            owner: "${{ github.repository_owner }}",
            repo: "${{ env.REPO_NAME }}",
            title: "Update context.tf",
            head: "${{ inputs.branch-name }}",
            base: "${{ github.ref }}",
            body: "${{ env.PR_BODY }}"
          });
        #delete-branch: true
        #labels: |
        #  auto-update
        #  context
