name: "github-action-terraform-auto-context"
description: "Automaticaly open a pull request to update context.tf for Terraform projects"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Update context.tf, checkout new branch, and commit new context.tf, if needed"
      shell: bash
      id: update
      env:
        GITHUB_TOKEN: "${{ inputs.token }}"
        BRANCH_NAME: "auto-update/context.tf"
      run: |
        if [[ -f context.tf ]]; then
          echo "Discovered existing context.tf!"
          echo "Checking for pre-existing ${BRANCH_NAME} branch."
          if ! [[ git rev-parse --quiet --verify ${BRANCH_NAME} > /dev/null ]]; then
            echo "Branch ${BRANCH_NAME} not found."
            echo "Fetching most recent version of context.tf to see if there is an update."
            curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
            if git diff --no-patch --exit-code context.tf; then
              echo "No changes detected! Exiting the job..."
            else
              # updating context.tf and documentation
              echo "context.tf file has changed. Update examples and rebuild README.md and commit everything to a new ${BRANCH_NAME} branch."
              make init
              make github/init/context.tf
              make readme/build
              # moving to new branch to commit changes
              git branch -avv
              git checkout -b auto-update/context.tf
              git branch -avv
              # committing changes
              git config --global user.name 'cloudpossebot'
              git config --global user.email '11232728+cloudpossebot@users.noreply.github.com'
              git add -A
              git commit -m "Update context.tf from origin source"
              git push --set-upstream origin ${BRANCH_NAME}
              # setting flag to create pull request for new branch
              echo "::set-output name=create_pull_request::true"
            fi
          else
            echo "Branch ${BRANCH_NAME} found."
            echo "Please merge pre-existing ${BRANCH_NAME} branch before rerunning this action."
          fi
        else
          echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
        fi

    - name: "Output pull request body"
      shell: bash
      run: |
        # Original comment:
        ### what
        #This is an auto-generated PR that updates the \`context.tf\` file to the latest version from \`cloudposse/terraform-null-label\`
        ### why
        #To support all the features of the \`context\` interface.
        COMMENT_BODY=$(cat << EOF
        This is an auto-generated PR that updates the context.tf file to the latest version from cloudposse/terraform-null-label.
        EOF
        )
        echo "COMMENT_BODY<<EOF" >> $GITHUB_ENV
        echo "$COMMENT_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: "Parse Repo Name"
      shell: bash
      env:
        FULL_REPO_NAME: ${{ github.repository }}
      run: |
        IFS='/' read -ra REPO_NAME_SPLIT <<< "$FULL_REPO_NAME"
        echo "${REPO_NAME_SPLIT[@]}"
        echo "REPO_NAME<<EOF" >> $GITHUB_ENV
        echo "${REPO_NAME_SPLIT[1]}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Pull Request
      if: steps.update.outputs.create_pull_request == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          // extract the base branch name that's being merged into
          //const prUrl = context.payload.schedule.pull_request.url;
          //const prDetails = await github.request(`GET ${prUrl}`);
          //let prBaseRef = prDetails.data.base.ref;
          let prBaseRef = context.ref;
          console.log(prBaseRef);
          console.log(context);

          // create pull request
          github.pulls.create({
            owner: "${{ github.repository_owner }}",
            repo: "${{ env.REPO_NAME }}",
            title: "Update context.tf",
            head: "auto-update/context.tf",
            base: "${{ github.ref }}",
            body: "${{ env.COMMENT_BODY }}"
          });
        #delete-branch: true
        #labels: |
        #  auto-update
        #  context
