name: "github-action-terraform-auto-context"
description: "Automaticaly open a pull request to update context.tf for Terraform projects"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Update context.tf, checkout new branch, and commit new context.tf, if needed"
      shell: bash
      id: update
      env:
        GITHUB_TOKEN: "${{ inputs.token }}"
      run: |
        if [[ -f context.tf ]]; then
          echo "Discovered existing context.tf! Fetching most recent version to see if there is an update."
          curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
          if git diff --no-patch --exit-code context.tf; then
            echo "No changes detected! Exiting the job..."
          else
            # updating context.tf and documentation
            echo "context.tf file has changed. Update examples and rebuild README.md."
            make init
            make github/init/context.tf
            make readme/build
            # moving to new branch to commit changes
            git branch -avv
            git checkout -b auto-update/context.tf
            git branch -avv
            # committing changes
            git config --global user.name 'cloudpossebot'
            git config --global user.email '11232728+cloudpossebot@users.noreply.github.com'
            git add -A
            git commit -m "Update context.tf from origin source"
            git push --set-upstream origin auto-update/context.tf
            # setting flag to create pull request for new branch
            echo "::set-output name=create_pull_request::true"
          fi
        else
          echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
        fi

    - name: "Output pull request body"
      shell: bash
      run: |
        ### what
        #This is an auto-generated PR that updates the \`context.tf\` file to the latest version from \`cloudposse/terraform-null-label\`
        ### why
        #To support all the features of the \`context\` interface.
        COMMENT_BODY=$(cat << EOF
        This is an auto-generated PR that updates the context.tf file to the latest version from cloudposse/terraform-null-label
        EOF
        )
        echo "COMMENT_BODY<<EOF" >> $GITHUB_ENV
        echo "$COMMENT_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Create Pull Request
      if: steps.update.outputs.create_pull_request == 'true'
      uses: actions/github-script@v4
      with:
        script: |
          // extract information about repo
          const {owner, repo} = context.schedule

          // extract the base branch name that's being merged into
          const prUrl = context.payload.schedule.pull_request.url;
          const prDetails = await github.request(`GET ${prUrl}`);
          let prBaseRef = prDetails.data.base.ref;

          // create pull request
          github.pulls.create({
            "cloudpossebot",
            repo,
            title: "Update context.tf",
            head: "auto-update/context.tf",
            base: prBaseRef,
            body: "${{ env.COMMENT_BODY }}"
          });
        #delete-branch: true
        #labels: |
        #  auto-update
        #  context
