name: "github-action-auto-context"
description: "Automaticaly open a pull request to update context.tf for Terraform projects"
inputs:
  branch-name:
    description: "Name of branch to commit updated context.tf to"
    required: false
    default: "auto-update/context.tf"
  token:
    description: "Token for authenticating to GitHub API server. No special permissions needed."
    required: true
  bot-name:
    decription: "Username to write commits under"
    required: false
    default: "cloudpossebot"
runs:
  using: "composite"
  steps:
    - name: "Checkout commit"
      uses: actions/checkout@v2

    - name: "Update context.tf, checkout new branch, and commit new context.tf, if needed"
      shell: bash
      id: update
      env:
        BRANCH_NAME: ${{ inputs.branch-name }}
        BOT_NAME: ${{ inputs.bot-name }}
      run: |
        if [[ -f context.tf ]]; then
          echo "Discovered existing context.tf!"
          echo "Checking for pre-existing ${BRANCH_NAME} branch."
          if [[ ! $(git show-branch remotes/origin/${BRANCH_NAME}) ]]; then
            echo "Branch ${BRANCH_NAME} not found."
            echo "Fetching most recent version of context.tf to see if there is an update."
            curl -o context.tf -fsSL https://raw.githubusercontent.com/cloudposse/terraform-null-label/master/exports/context.tf
            if git diff --no-patch --exit-code context.tf; then
              echo "No changes detected! Exiting the job..."
            else
              # updating context.tf and documentation
              echo "context.tf file has changed. Update examples and rebuild README.md and commit everything to a new ${BRANCH_NAME} branch."
              make init
              make github/init/context.tf
              make readme/build
              # moving to new branch to commit changes
              git checkout -b ${BRANCH_NAME}
              # committing changes
              git config --global user.name "${BOT_NAME}"
              git config --global user.email "11232728+${BOT_NAME}@users.noreply.github.com"
              git add -A
              git commit -m "Update context.tf from origin source"
              git push --set-upstream origin ${BRANCH_NAME}
              # setting flag to create pull request for new branch
              echo "::set-output name=create_pull_request::true"
            fi
          else
            echo "Branch ${BRANCH_NAME} found."
            echo "Please merge or delete pre-existing ${BRANCH_NAME} branch before rerunning this action."
          fi
        else
          echo "This module has not yet been updated to support the context.tf pattern! Please update in order to support automatic updates."
        fi

    - name: Create Pull Request
      if: steps.update.outputs.create_pull_request == 'true'
      uses: cloudposse/actions/github/create-pull-request@0.30.0
      with:
        token: ${{ inputs.token }}
        committer: '${{ inputs.bot-name }} <11232728+${{ inputs.bot-name }}@users.noreply.github.com>'
        author: '${{ inputs.bot-name }} <11232728+${{ inputs.bot-name }}@users.noreply.github.com>'
        commit-message: Update context.tf from origin source
        title: Update context.tf
        body: |-
          ## what
          This is an auto-generated PR that updates the `context.tf` file to the latest version from `cloudposse/terraform-null-label`
          ## why
          To support all the features of the `context` interface.
        branch: auto-update/context.tf
        base: main
        delete-branch: true
        labels: |
          auto-update
          context
