name: "auto-context"
on:
  schedule:
  # Update context.tf nightly (assuming your time zone is GMT-7)
  - cron:  '0 7 * * *'
  workflow_dispatch:

jobs:
  auto-context:
    runs-on: ubuntu-latest
    steps:
    - uses: cloudposse/github-action-terraform-auto-context/.github/workflows/auto-context-reusable@improve-bot-email-default
      with:
        branch-name: ${{ inputs.branch-name }}
        bot-name: ${{ inputs.bot-name }}
        bot-email: ${{ inputs.bot-email }}
        token: ${{ secrets.GITHUB_TOKEN }}
