name: "auto-context"
on:
  schedule:
  # Update context.tf nightly (assuming your time zone is GMT-7)
  - cron:  '0 7 * * *'
  workflow_dispatch:

jobs:
  auto-context:
    uses: cloudposse/github-action-terraform-auto-context/.github/workflows/auto-context-reusable.yml@main
    with:
      # Name of branch to commit updated context.tf to
      branch-name: auto-update/context.tf
      # GitHub username to use for automated commits (should be a real GitHub user)
      bot-name: cloudpossebot
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
